-- ---------------------------
-- 22 Advanced Business Problems
-- ---------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/


/*ALTER TABLE order_items
ADD COLUMN sales_value FLOAT;

UPDATE order_items
SET sales_value = quantity * price_per_unit;*/

WITH cte as(SELECT product_name,SUM(quantity) total_quantity_sold,SUM(sales_value) as total_sales_value,
DENSE_RANK() OVER(ORDER BY SUM(sales_value) DESC) rn
FROM products p
JOIN order_items o 
ON p.product_id=o.product_id
GROUP BY product_name)

SELECT product_name,total_quantity_sold,total_sales_value
FROM cte
WHERE rn<=10;

 
/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

WITH cte as(SELECT c.category_id,category_name,ROUND(SUM(quantity*price)::numeric,2) total_revenue
FROM products p
LEFT JOIN order_items o
ON p.product_id=o.product_id
JOIN category c
ON c.category_id=p.category_id
GROUP BY c.category_id,category_name)

SELECT category_id,category_name,total_revenue,
ROUND((total_revenue/(SELECT SUM(total_revenue) FROM cte))*100.0::numeric,2) percent_of_total_sales
FROM cte
ORDER BY category_id;


/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

-- AOV = TR/No of orders

WITH cte AS(SELECT customer_id,SUM(sales_value) total_sales_value,COUNT(customer_id) no_of_orders
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY customer_id
HAVING COUNT(customer_id)>5)

SELECT c.customer_id,first_name,last_name,round((total_sales_value/no_of_orders)::numeric,2) total_order_value,no_of_orders
FROM cte c
LEFT JOIN customers cu
ON cu.customer_id=c.customer_id
ORDER BY c.customer_id;

/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/
WITH t1 AS
(SELECT substring(order_date::TEXT from 1 for 7) month_year,
ROUND(SUM(sales_value)::NUMERIC,2) sales_value_per_month 
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
WHERE order_date > (CURRENT_DATE - INTERVAL '1 year')::DATE 
GROUP BY 1 
ORDER BY 1)

SELECT month_year, sales_value_per_month AS current_month_sales,
LAG(sales_value_per_month) OVER(ORDER BY month_year) previous_month_sales,
ROUND(((sales_value_per_month / LAG(sales_value_per_month) OVER(ORDER BY month_year)) -1)*100, 2) percent_change
FROM t1

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/


SELECT customer_id,first_name,last_name
FROM customers
WHERE customer_id NOT IN(SELECT customer_id FROM orders);

/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/

WITH cte AS(SELECT category_name,state,round(SUM(sales_value)::numeric,2) total_sales,
DENSE_RANK() OVER(PARTITION BY state ORDER BY SUM(sales_value)) rn
FROM order_items oi
JOIN products p
ON oi.product_id=p.product_id
JOIN category c
ON c.category_id=p.category_id
JOIN orders o
ON o.order_id=oi.order_id
JOIN customers cu
ON o.customer_id=cu.customer_id
GROUP BY 1,2
ORDER BY 2)

SELECT category_name,state,total_sales
FROM cte
WHERE rn=1;

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

SELECT c.customer_id,first_name,last_name,round(SUM(sales_value)::numeric,2) total_sales,
DENSE_RANK() OVER(ORDER BY SUM(sales_value) DESC) rank
FROM order_items oi
JOIN orders o
ON o.order_id=oi.order_id
JOIN customers c
ON c.customer_id=o.customer_id
GROUP BY 1,2,3;


/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT i.product_id,product_name,stock,warehouse_id,last_stock_date
FROM inventory i
LEFT JOIN products p 
ON p.product_id=i.product_id
WHERE stock<10;

/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

SELECT cu.customer_id,first_name,last_name,order_date,shipping_date-order_date days_to_ship,seller_name
FROM shipping s
JOIN orders o
ON o.order_id=s.order_id
JOIN customers cu
ON cu.customer_id=o.customer_id
JOIN sellers se
ON se.seller_id=o.seller_id
WHERE shipping_date-order_date>3;


/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT DISTINCT payment_status,COUNT(payment_status),
round((COUNT(payment_status)*1.0/(SELECT COUNT(*) FROM payments))*100.0::numeric,2) percent_contribution
FROM payments
GROUP BY payment_status;


/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/


SELECT s.seller_id,seller_name,round(SUM(sales_value)::numeric,2) total_sales_value,
COUNT(CASE WHEN order_status='Completed' THEN 1 END)  successful_orders,
COUNT(CASE WHEN order_status='Returned' OR order_status='Cancelled' THEN 1 END) failed_orders,
round((COUNT(CASE WHEN order_status='Completed' THEN 1 END)*1.0)/COUNT(order_status)*100.0::numeric,2) success_percent
FROM sellers s JOIN orders o ON o.seller_id=s.seller_id
JOIN order_items oi on oi.order_id=o.order_id
GROUP BY 1
ORDER BY 3 DESC
LIMIT 5;

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

SELECT product_id,product_name,(price-cogs)/price*100.0 profit_margin,
DENSE_RANK() OVER(ORDER BY (price-cogs)/price*100.0 DESC) rank
FROM products;


/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/

SELECT oi.product_id,product_name,
COUNT(CASE WHEN order_status='Returned' THEN order_status END) no_of_returns,
round((COUNT(CASE WHEN order_status='Returned' THEN order_status END)*1.0)/COUNT(product_name)*100.0::numeric,2) return_rate
FROM orders o
JOIN order_items oi ON o.order_id=oi.order_id
JOIN products p ON p.product_id=oi.product_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10;

/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/

SELECT o.order_id,first_name,last_name,order_status,payment_date
FROM orders o
JOIN payments p
ON o.order_id=p.order_id
JOIN customers c
ON c.customer_id=o.customer_id
WHERE payment_status='Payment Successed' AND order_status='Inprogress';


/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/

SELECT o.seller_id,seller_name,MAX(order_date) last_sale_date,SUM(sales_value) total_sales
FROM orders o
JOIN sellers s ON s.seller_id=o.seller_id
JOIN order_items oi ON oi.order_id=o.order_id
WHERE order_date BETWEEN (SELECT MAX(order_date) - INTERVAL '6 months' FROM orders) AND
(SELECT MAX(order_date) FROM orders)
GROUP BY 1,2;

/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/

WITH cte AS(SELECT customer_id,COUNT(customer_id) total_orders,
COUNT(CASE WHEN order_status='Returned' THEN 1 END) no_of_returns,
CASE WHEN order_status='Returned' AND COUNT(order_status)>5 THEN 'Returning' ELSE 'New' END customer_category
FROM orders
GROUP BY 1,order_status='Returned')

SELECT c.customer_id,first_name||' '||last_name customer_name,customer_category,no_of_returns,total_orders
FROM cte c
JOIN customers cu
ON c.customer_id=cu.customer_id;


/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/

WITH cte as(SELECT o.customer_id,first_name,last_name,state,COUNT(o.order_id) no_of_orders,
round(SUM(sales_value)::numeric,2) total_sales_value,
DENSE_RANK() OVER(PARTITION BY state ORDER BY COUNT(o.order_id) DESC) rank
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY 4,1,2,3)

SELECT *
FROM cte
WHERE rank<6;

/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.*/

SELECT shipping_providers,round(SUM(sales_value)::numeric,2) total_revenue,round(COUNT(oi.order_id)::numeric,2) total_orders,
round(AVG(CASE WHEN deliver_status='Delivered' THEN shipping_date-order_date END)::numeric,2) avg_delivery_time
FROM shipping s
JOIN order_items oi
ON s.order_id=oi.order_id
JOIN orders o
ON o.order_id=oi.order_id AND o.order_id=s.order_id
GROUP BY 1;


/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result

Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/


WITH cte AS(SELECT p.product_id,product_name,p.category_id,category_name,
SUM(CASE WHEN EXTRACT(YEAR FROM order_date)=2022 THEN sales_value END) year_2022,
SUM(CASE WHEN EXTRACT(YEAR FROM order_date)=2023 THEN sales_value END) year_2023
FROM products p
JOIN category c
ON c.category_id=p.category_id
JOIN order_items oi
ON oi.product_id=p.product_id
JOIN orders o
ON o.order_id=oi.order_id
GROUP BY 1,2,3,4)

SELECT *,round(((year_2023-year_2022)/(year_2022)*100.0)::numeric,2) AS percentage_difference
FROM cte
ORDER BY 7
LIMIT 10;


-- STORED PROCEDURE
/*
Final Task
-- Store Procedure
create a function as soon as the product is sold the the same quantity should reduced from inventory table
after adding any sales records it should update the stock in the inventory table based on the product and qty purchased
-- 
*/

CREATE OR REPLACE PROCEDURE sales (i_product_id INT, i_order_id INT, i_order_item_id INT,
								   i_customer_id INT, i_seller_id INT,  i_quantity INT)
LANGUAGE plpgsql
AS
$$
DECLARE
v_count INT;
v_price FLOAT;
v_product_name VARCHAR(100);

BEGIN
SELECT price, product_name INTO v_price, v_product_name
FROM products
WHERE product_id = i_product_id;

SELECT COUNT(*) INTO v_count
FROM inventory
WHERE product_id = i_product_id AND stock > i_quantity;

IF v_count > 0 THEN
	INSERT INTO orders (order_id, order_date, customer_id, seller_id, order_status)
	VALUES (i_order_id, CURRENT_DATE, i_customer_id, i_seller_id, 'Inprogress');
	
	INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price_per_unit, sales_value)
	VALUES (i_order_item_id, i_order_id, i_product_id, i_quantity, v_price, v_price * i_quantity);
	
	UPDATE inventory
	SET stock = stock - i_quantity
	WHERE product_id = i_product_id;
	
	RAISE NOTICE 'Sale of product has been updated';
	
ELSE
 	RAISE NOTICE 'Inadequate stock quantity';
END IF;
COMMIT;
END;
$$


CALL sales (5 ,25000, 25000, 500, 50, 35)

